[tools]
terraform = "1.11.1"
terraform-docs = "0.19.0"
tflint = "0.55.1"

[tasks."terraform:init"]
description = "Initializes Terraform"
depends = ["terraform:init:nodepool"]
run = "terraform init"

[tasks."terraform:init:nodepool"]
description = "Initializes Terraform"
run = "terraform init"
dir = "{{ config_root }}/modules/nodepool"

[tasks."terraform:validate"]
description = "Validates the Terraform files"
depends = ["terraform:init", "terraform:validate:nodepool"]
run = "terraform validate"

[tasks."terraform:validate:nodepool"]
description = "Validates the Terraform files"
run = "terraform validate"
depends = ["terraform:init:nodepool"]
dir = "{{ config_root }}/modules/nodepool"

[tasks."terraform:format"]
description = "Formats the Terraform files"
depends = ["terraform:format:nodepool"]
run = "terraform fmt"

[tasks."terraform:format:nodepool"]
description = "Formats the Terraform files"
run = "terraform fmt"
dir = "{{ config_root }}/modules/nodepool"

[tasks."tfdocs:generate"]
description = "Generates Terraform documentation"
depends = ["tfdocs:generate:nodepool"]
run = "terraform-docs markdown . > README.md"

[tasks."tfdocs:generate:nodepool"]
description = "Generates Terraform documentation for the nodepool module"
dir = "{{ config_root }}/modules/nodepool"
run = "terraform-docs markdown . > README.md"